---

- name: install openvpn
  apt: name=openvpn state=present

- name: install ca cert
  copy: src=ca.crt dest=/etc/openvpn/ca.crt

- name: install premiumize configs
  template: src=premiumize.ovpn dest="/etc/openvpn/premiumize-{{ item }}.conf"
  with_items:
    - us
    - gb
    - sw
    - nl

- name: write creds
  template: src=openvpn-login dest=/etc/openvpn/login mode="u=r,g=,o=" owner=root

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- name: ipv4 forward
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

# Set up the firewall
- name: install iptables-persistent for Debian
  apt: pkg=iptables-persistent state=present

- name: copy rules.v4
  copy: src=rules.v4 dest=/etc/iptables/rules.v4

- name: copy rules.v6
  copy: src=rules.v6 dest=/etc/iptables/rules.v6

- name: enable netfilter-persistent on boot
  service: name=netfilter-persistent enabled=yes
