---

- name: install openvpn
  apt: name=openvpn state=present
  tags: openvpn

- name: install config
  template: src={{ openvpn_ovpn }} dest="/etc/openvpn/custom.conf"
  tags: openvpn

- name: install openvpn default
  template: src=default_openvpn dest=/etc/default/openvpn owner=root
  tags: openvpn
